[2024-05-25T04:43:23.984+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-25T04:43:23.998+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Customer_Prosensity_DAG.starting manual__2024-05-25T04:43:22.435397+00:00 [queued]>
[2024-05-25T04:43:24.003+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Customer_Prosensity_DAG.starting manual__2024-05-25T04:43:22.435397+00:00 [queued]>
[2024-05-25T04:43:24.003+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 6
[2024-05-25T04:43:24.012+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): starting> on 2024-05-25 04:43:22.435397+00:00
[2024-05-25T04:43:24.017+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=70) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-25T04:43:24.017+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Customer_Prosensity_DAG', 'starting', 'manual__2024-05-25T04:43:22.435397+00:00', '--job-id', '4419', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_customer_sqlite3.py', '--cfg-path', '/tmp/tmprnor6p0w']
[2024-05-25T04:43:24.018+0000] {standard_task_runner.py:63} INFO - Started process 72 to run task
[2024-05-25T04:43:24.018+0000] {standard_task_runner.py:91} INFO - Job 4419: Subtask starting
[2024-05-25T04:43:24.048+0000] {task_command.py:426} INFO - Running <TaskInstance: Customer_Prosensity_DAG.starting manual__2024-05-25T04:43:22.435397+00:00 [running]> on host cb453a136ab9
[2024-05-25T04:43:24.108+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='NhơnVõ' AIRFLOW_CTX_DAG_ID='Customer_Prosensity_DAG' AIRFLOW_CTX_TASK_ID='starting' AIRFLOW_CTX_EXECUTION_DATE='2024-05-25T04:43:22.435397+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-25T04:43:22.435397+00:00'
[2024-05-25T04:43:24.109+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-25T04:43:24.110+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-05-25T04:43:24.110+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo "starting data . . ."']
[2024-05-25T04:43:24.117+0000] {subprocess.py:86} INFO - Output:
[2024-05-25T04:43:24.118+0000] {subprocess.py:93} INFO - starting data . . .
[2024-05-25T04:43:24.118+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-05-25T04:43:24.119+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-25T04:43:24.135+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=Customer_Prosensity_DAG, task_id=starting, run_id=manual__2024-05-25T04:43:22.435397+00:00, execution_date=20240525T044322, start_date=20240525T044323, end_date=20240525T044324
[2024-05-25T04:43:24.151+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-25T04:43:24.171+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-05-25T04:43:24.172+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
